# Dracula theme for Starship prompt

[character]
success_symbol = "â¯"
error_symbol = "âœ—"
vicmd_symbol = "â®"
style = "bold #f8f8f2"

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold #bd93f9"

[git_status]
conflicted = "ğŸ”¥"
ahead = "â‡¡"
behind = "â‡£"
diverged = "â†¯"
untracked = "?"
stashed = "âš‘"
modified = "*"
staged = "+"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #f8f8f2"
read_only = " ï€£"

[hostname]
style = "bold #ff79c6"
format = "[$hostname]($style) "

[time]
format = "at [$time]($style) "
disabled = false
time_format = "%H:%M:%S"
style = "bold #f8f8f2"