[character]
success_symbol = "â¯"
error_symbol = "âœ—"
vicmd_symbol = "â®"
style = "bold #D8DEE9"

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold #81A1C1"

[git_status]
conflicted = "ğŸ”¥"
ahead = "â‡¡"
behind = "â‡£"
diverged = "â†¯"
untracked = "?"
stashed = "âš‘"
modified = "*"
staged = "+"

[cmd_duration]
style = "bold #EBCB8B"

[directory]
style = "bold #D8DEE9"
read_only = " ï€£"

[hostname]
style = "bold #B48EAD"
format = "[$hostname]($style) "

[time]
format = "at [$time]($style) "
disabled = false
time_format = "%H:%M:%S"
style = "bold #D8DEE9"